### PR TITLE
Add java 8 stream sample

### PR DESCRIPTION
**Pull request by yogesh147**
demonstration of java 8 Stream API in java

### CODE REVIEW

**Comment by yogesh147** [comment]
demonstration of java 8 Stream API in java

**Comment by yogesh147** [comment]
sample for java Time API

**Comment by yogesh147** [comment]
sample for java Time API

**Comment by yogesh147** [comment]
Sample code for using lambda expression

**Review by sushish-kumar — COMMENTED** [review]
Include the changes in a folder named appropriately. Other seems good.

**Pull request merged**
